version: '3.7'
services:
  haproxy:
    image: haproxy:2.5-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/:ro
    networks:
      - default
    restart: unless-stopped
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=$PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      - default
  calpol:
    image: ghcr.io/jacob-pro/calpol:latest
    volumes:
      - type: bind
        source: ./calpol.toml
        target: /etc/calpol/config.toml
    environment:
      - API_PORT=80
      - DATABASE_URL=postgres://postgres:$PASSWORD@postgres:5432/postgres
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - default
volumes:
  postgres:
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
