openapi: 3.0.3
info:
  title: calpol
  description: Multi-Service health monitor
  contact:
    name: Jacob Halsey
    email: jacob@jhalsey.com
  license:
    name: ''
  version: 0.1.0
paths:
  /v1/re_run:
    post:
      tags:
      - re_run
      summary: Request test runner to immediately re-run.
      description: |
        Request test runner to immediately re-run.
      operationId: requestReRun
      responses:
        '200':
          description: Success
        default:
          description: Success
      deprecated: false
  /v1/runner_logs:
    get:
      tags:
      - runner_logs
      summary: List the test runner logs
      description: |
        List the test runner logs
      operationId: listRunnerLogs
      responses:
        '200':
          description: List of test runner logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRunnerLogsResponse'
      deprecated: false
components:
  schemas:
    ListRunnerLogsResponse:
      type: object
      required:
      - items
      - total
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/RunnerLog'
        total:
          type: integer
          format: int64
    RunnerLog:
      type: object
      required:
      - id
      - time_started
      - time_finished
      properties:
        failure_reason:
          type: string
        id:
          type: integer
          format: int32
        tests_failed:
          type: integer
          format: int32
        tests_passed:
          type: integer
          format: int32
        tests_skipped:
          type: integer
          format: int32
        time_finished:
          type: string
          format: date-time
        time_started:
          type: string
          format: date-time
  responses:
    ApiError:
      description: An Api Problem (RFC7807)
      content:
        application/json:
          schema:
            type: object
            title: ApiError
            properties:
              detail:
                type: string
                description: |
                  A human readable explanation specific to this occurrence of the
                  problem.
                example: Connection to database timed out
              instance:
                type: string
                description: |
                  An absolute URI that identifies the specific occurrence of the problem.
                  It may or may not yield further information if dereferenced.
              status:
                type: integer
                format: int32
                description: |
                  The HTTP status code generated by the origin server for this occurrence
                  of the problem.
                example: 503
              title:
                type: string
                description: |
                  A short, summary of the problem type. Written in english and readable
                  for engineers (usually not suited for non technical stakeholders and
                  not localized); example: Service Unavailable
              type:
                type: string
                description: |
                  An absolute URI that identifies the problem type.  When dereferenced,
                  it SHOULD provide human-readable documentation for the problem type
                  (e.g., using HTML).
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
security:
- basicAuth: []
