---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Calpol API
security:
  - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
  # Reusable responses, such as 401 Unauthorized or 400 Bad Request
  responses:
    ApiError:
      description: An Api Problem (RFC7807)
      content:
        application/json:
          schema:
            type: object
            title: ApiError
            additionalProperties: true
            properties:
              type:
                type: string
                format: uri
                description: |
                  An absolute URI that identifies the problem type.  When dereferenced,
                  it SHOULD provide human-readable documentation for the problem type
                  (e.g., using HTML).
              title:
                type: string
                description: |
                  A short, summary of the problem type. Written in english and readable
                  for engineers (usually not suited for non technical stakeholders and
                  not localized); example: Service Unavailable
              status:
                type: integer
                format: int32
                description: |
                  The HTTP status code generated by the origin server for this occurrence
                  of the problem.
                minimum: 100
                maximum: 600
                exclusiveMaximum: true
                example: 503
              detail:
                type: string
                description: |
                  A human readable explanation specific to this occurrence of the
                  problem.
                example: Connection to database timed out
              instance:
                type: string
                format: uri
                description: |
                  An absolute URI that identifies the specific occurrence of the problem.
                  It may or may not yield further information if dereferenced.
  # Reusable schemas (data models)
  schemas:
    PaginatedResponse:
      type: object
      required:
        - next_page
      properties:
        next_page:
          type: string
    PaginatedRequest:
      type: object
      properties:
        page_token:
          type: string
    SearchableRequest:
      type: object
      properties:
        search:
          type: string
    User:
      type: object
      required:
        - id
        - name
        - email
        - sms_notifications
        - email_notifications
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        sms_notifications:
          type: boolean
        email_notifications:
          type: boolean
    Session:
      type: object
      required:
        - id
        - created
        - last_used
        - last_ip
        - user_agent
      properties:
        id:
          type: integer
          format: int32
        created:
          type: integer
          format: int64
        last_used:
          type: integer
          format: int64
        last_ip:
          type: string
        user_agent:
          type: string
    Test:
      type: object
      required:
        - name
        - config
        - enabled
        - failure_threshold
        - failing
      properties:
        name:
          type: string
        config:
          type: object
        enabled:
          type: boolean
        failure_threshold:
          type: integer
          minimum: 1
          maximum: 50
        failing:
          type: boolean
    TestResult:
      type: object
      required:
        - test_name
        - time_started
        - time_finished
      properties:
        test_name:
          type: string
        failure_reason:
          type: string
        time_started:
          type: integer
          format: int64
        time_finished:
          type: integer
          format: int64
paths:
  "/v1/sessions/login":
    post:
      operationId: login
      tags:
        - sessions
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: LoginRequest
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: The logged in user
          content:
            application/json:
              schema:
                type: object
                title: LoginResponse
                properties:
                  token:
                    type: string
                  user:
                    "$ref": "#/components/schemas/User"
                  session:
                    "$ref": "#/components/schemas/Session"
                required:
                  - token
                  - user
                  - session
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/sessions/logout":
    delete:
      operationId: logout
      tags:
        - sessions
      responses:
        '200':
          description: Success
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/sessions":
    get:
      operationId: listSessions
      tags:
        - sessions
      responses:
        '200':
          description: List of the users sessions
          content:
            application/json:
              schema:
                type: object
                title: ListSessionsResponse
                allOf:
                  - "$ref": "#/components/schemas/PaginatedResponse"
                  - type: object
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        items:
                          "$ref": "#/components/schemas/Session"
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/sessions/{id}":
    delete:
      operationId: deleteSession
      tags:
        - sessions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/users":
    get:
      operationId: listUsers
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: ListUsersRequest
              allOf:
                - "$ref": "#/components/schemas/PaginatedRequest"
                - "$ref": "#/components/schemas/SearchableRequest"
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: object
                title: ListUsersResponse
                allOf:
                  - "$ref": "#/components/schemas/PaginatedResponse"
                  - type: object
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        items:
                          "$ref": "#/components/schemas/User"
        'default':
          "$ref": "#/components/responses/ApiError"
    post:
      operationId: createUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: CreateUserRequest
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 255
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Create user response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/users/{id}":
    get:
      operationId: getUser
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Get user response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        'default':
          "$ref": "#/components/responses/ApiError"
    put:
      operationId: updateUser
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: UpdateUserRequest
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 255
                email:
                  type: string
                  format: email
                phone:
                  type: string
                  format: phone
                  nullable: true
                sms_notifications:
                  type: boolean
                email_notifications:
                  type: boolean
      responses:
        '200':
          description: Update user response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        'default':
          "$ref": "#/components/responses/ApiError"
    delete:
      operationId: deleteUser
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/tests":
    get:
      operationId: listTests
      tags:
        - tests
      responses:
        '200':
          description: List of tests
          content:
            application/json:
              schema:
                type: object
                title: ListTestsResponse
                allOf:
                  - type: object
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        items:
                          "$ref": "#/components/schemas/Test"
        'default':
          "$ref": "#/components/responses/ApiError"
    post:
      operationId: createTest
      tags:
        - tests
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: CreateTestRequest
              required:
                - name
                - config
              properties:
                name:
                  type: string
                config:
                  type: object
                enabled:
                  type: boolean
                failure_threshold:
                  type: integer
                  minimum: 1
                  maximum: 50
      responses:
        '200':
          description: Create test response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Test"
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/tests/{test_name}":
    get:
      operationId: getTest
      tags:
        - tests
      parameters:
        - name: test_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get test response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Test"
        'default':
          "$ref": "#/components/responses/ApiError"
    put:
      operationId: updateTest
      tags:
        - tests
      parameters:
        - name: test_name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: UpdateTestRequest
              properties:
                config:
                  type: object
                enabled:
                  type: boolean
                failure_threshold:
                  type: integer
                  minimum: 1
                  maximum: 50
      responses:
        '200':
          description: Update test response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Test"
        'default':
          "$ref": "#/components/responses/ApiError"
    delete:
      operationId: deleteTest
      tags:
        - tests
      parameters:
        - name: test_name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/test_results":
    get:
      operationId: listTestResults
      tags:
        - test_results
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: ListTestResultsRequest
              allOf:
                - "$ref": "#/components/schemas/PaginatedRequest"
                - type: object
                  properties:
                    test_name:
                      type: string
      responses:
        '200':
          description: Test results list
          content:
            application/json:
              schema:
                type: object
                title: ListTestResultsResponse
                allOf:
                  - "$ref": "#/components/schemas/PaginatedResponse"
                  - type: object
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        items:
                          "$ref": "#/components/schemas/TestResult"
        'default':
          "$ref": "#/components/responses/ApiError"
  "/v1/test_results/summary":
    get:
      operationId: summarizeTestResults
      tags:
        - test_results
      responses:
        '200':
          description: Test results summary
          content:
            application/json:
              schema:
                type: object
                title: SummarizeTestResultsResponse
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      "$ref": "#/components/schemas/TestResult"
        'default':
          "$ref": "#/components/responses/ApiError"
